# Generated by Django 3.2.12 on 2024-02-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20240213_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimage',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
