# Generated by Django 3.2.12 on 2024-02-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='caption',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default='', upload_to='static/images/blog'),
            preserve_default=False,
        ),
    ]
