# Generated by Django 3.2.12 on 2024-02-13 14:41

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20240213_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
