# Generated by Django 3.2.12 on 2024-02-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_blogpost_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='aurthor',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
