# Generated by Django 3.2.12 on 2024-02-18 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_blogpost_aurthor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
